theme:
  container:
    center: true
    padding: "2rem"
    screens:
      "2xl": "1400px"
  extend:
    borderRadius:
      lg: "0.5rem"
      md: "calc(0.5rem - 2px)"
      sm: "calc(0.5rem - 4px)"
    colors:
      border: "hsl(240, 5.9%, 90%)"
      input: "hsl(240, 5.9%, 90%)"
      ring: "hsl(240, 10%, 3.9%)"
      background: "hsl(0, 0%, 100%)"
      foreground: "hsl(240, 10%, 3.9%)"
      primary:
        DEFAULT: "hsl(240, 5.9%, 10%)"
        foreground: "hsl(0, 0%, 98%)"
      secondary:
        DEFAULT: "hsl(240, 4.8%, 95.9%)"
        foreground: "hsl(240, 5.9%, 10%)"
      destructive:
        DEFAULT: "hsl(0, 84.2%, 60.2%)"
        foreground: "hsl(0, 0%, 98%)"
      muted:
        DEFAULT: "hsl(240, 4.8%, 95.9%)"
        foreground: "hsl(240, 3.8%, 46.1%)"
      accent:
        DEFAULT: "hsl(240, 4.8%, 95.9%)"
        foreground: "hsl(240, 5.9%, 10%)"
      popover:
        DEFAULT: "hsl(0, 0%, 100%)"
        foreground: "hsl(240, 10%, 3.9%)"
      card:
        DEFAULT: "hsl(0, 0%, 100%)"
        foreground: "hsl(240, 10%, 3.9%)"
  tokens:
    light:
      border: "hsl(240, 5.9%, 90%)"
      input: "hsl(240, 5.9%, 90%)"
      ring: "hsl(240, 10%, 3.9%)"
      background: "hsl(0, 0%, 100%)"
      foreground: "hsl(240, 10%, 3.9%)"
      primary: "hsl(240, 5.9%, 10%)"
      primary-foreground: "hsl(0, 0%, 98%)"
      secondary: "hsl(240, 4.8%, 95.9%)"
      secondary-foreground: "hsl(240, 5.9%, 10%)"
      destructive: "hsl(0, 84.2%, 60.2%)"
      destructive-foreground: "hsl(0, 0%, 98%)"
      muted: "hsl(240, 4.8%, 95.9%)"
      muted-foreground: "hsl(240, 3.8%, 46.1%)"
      accent: "hsl(240, 4.8%, 95.9%)"
      accent-foreground: "hsl(240, 5.9%, 10%)"
      popover: "hsl(0, 0%, 100%)"
      popover-foreground: "hsl(240, 10%, 3.9%)"
      card: "hsl(0, 0%, 100%)"
      card-foreground: "hsl(240, 10%, 3.9%)"
    dark:
      border: "hsl(240, 3.7%, 15.9%)"
      input: "hsl(240, 3.7%, 15.9%)"
      ring: "hsl(240, 4.9%, 83.9%)"
      background: "hsl(240, 10%, 3.9%)"
      foreground: "hsl(0, 0%, 98%)"
      primary: "hsl(0, 0%, 98%)"
      primary-foreground: "hsl(240, 5.9%, 10%)"
      secondary: "hsl(240, 3.7%, 15.9%)"
      secondary-foreground: "hsl(0, 0%, 98%)"
      destructive: "hsl(0, 62.8%, 30.6%)"
      destructive-foreground: "hsl(0, 0%, 98%)"
      muted: "hsl(240, 3.7%, 15.9%)"
      muted-foreground: "hsl(240, 5%, 64.9%)"
      accent: "hsl(240, 3.7%, 15.9%)"
      accent-foreground: "hsl(0, 0%, 98%)"
      popover: "hsl(240, 10%, 3.9%)"
      popover-foreground: "hsl(0, 0%, 98%)"
      card: "hsl(240, 10%, 3.9%)"
      card-foreground: "hsl(0, 0%, 98%)"
screens:
  sm: "640px"
  md: "768px"
  lg: "1024px"
  xl: "1280px"
  "2xl": "1536px"
